name: Docker Image CI - X86_64/AARCH64 for Alpine/Chimera Linux to continuous tags

on:
  push:
    branches: [ "main" ]
    tags:
      - 'continuous'    
  pull_request:
    branches: [ "main" ]
  # run it manually
  workflow_dispatch:     
  schedule:
    - cron: "21 12 * * *"  
    - cron: "46 0 * * *"  

jobs:

  build:
    
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        dockeros: [alpine, chimera]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f Dockerfile-${{ matrix.dockeros }} --tag builder .

    - name: build static program with alpine linux docker 
      run: |
        docker run --cidfile=builder.cid builder true
        docker cp "$(cat builder.cid):work/artifact/." .

    - name: Upload althttpd binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./*.tar.xz
        tag: refs/tags/continuous
        overwrite: true
        file_glob: true
        body: "Fully static althttpd binary using alpine/chimera linux docker containers"       
